# Generated by Django 4.2.7 on 2023-11-25 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('banner', models.URLField(blank=True, null=True)),
                ('icono', models.URLField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('0', 'Sin categoria'), ('1', 'Comida Mexicana'), ('2', 'Comida Italiana'), ('3', 'Comida Asiatica'), ('4', 'Comida Rapida'), ('5', 'Hamburguesas'), ('6', 'Cafeteria'), ('7', 'Barbacoa'), ('8', 'Vegetariano'), ('9', 'Vegano'), ('10', 'Postres'), ('11', 'Pizza'), ('12', 'Sushi')], default=0, max_length=2)),
                ('promedio_calific', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
