# Generated by Django 4.2.7 on 2023-11-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_alter_restaurante_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='categoria',
            field=models.CharField(choices=[('0', 'Sin categoria'), ('1', 'Comida Mexicana'), ('2', 'Comida Italiana'), ('3', 'Comida Asiatica'), ('4', 'Comida Rapida'), ('5', 'Hamburguesas'), ('6', 'Cafeteria'), ('7', 'Barbacoa'), ('8', 'Vegetariano'), ('9', 'Vegano'), ('10', 'Postres'), ('11', 'Pizza'), ('12', 'Sushi')], default=0, max_length=2),
        ),
    ]
