# Generated by Django 4.2.7 on 2023-11-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0004_restaurante_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='promedio_calific',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
