# Generated by Django 4.2.7 on 2023-11-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0007_alter_restaurante_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
