# Generated by Django 4.2.7 on 2023-12-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='review',
            name='contenido',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
