# Generated by Django 4.2.7 on 2023-11-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('0', 'Sin categoría'), ('1', 'Frutas'), ('2', 'Carnes'), ('3', 'Mariscos'), ('4', 'Postres'), ('5', 'Especias y Condimentos'), ('6', 'Productos Organicos'), ('7', 'Bebidas'), ('8', 'Aves'), ('9', 'Helados'), ('10', 'Comida Japonesa')], default=0, max_length=2)),
                ('estado', models.CharField(choices=[('1', 'En Stock'), ('2', 'Agotado')], default=1, max_length=2)),
                ('promedio_calific', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('proveedores', models.ManyToManyField(blank=True, to='proveedores.proveedor')),
                ('restaurantes', models.ManyToManyField(blank=True, to='restaurantes.restaurante')),
            ],
        ),
    ]
