# Generated by Django 4.2.7 on 2023-11-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_propietario'),
        ('restaurantes', '0002_restaurante_propietario'),
        ('productos', '0002_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='restaurante',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='restaurantes',
            field=models.ManyToManyField(blank=True, to='restaurantes.restaurante'),
        ),
    ]
