# Generated by Django 4.2.7 on 2023-11-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('0', 'Sin categoría'), ('1', 'Frutas'), ('2', 'Carnes'), ('3', 'Mariscos'), ('4', 'Postres'), ('5', 'Especias y Condimentos'), ('6', 'Productos Organicos'), ('7', 'Bebidas'), ('8', 'Aves'), ('9', 'Helados'), ('10', 'Comida Japonesa')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
