# Generated by Django 4.2.7 on 2023-11-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_promedio_calific'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
