# Generated by Django 4.2.7 on 2023-11-25 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('banner', models.URLField(blank=True, null=True)),
                ('icono', models.URLField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(choices=[('0', 'Sin categoría'), ('1', 'Proveedor de Frutas'), ('2', 'Carnicería'), ('3', 'Pescadería'), ('4', 'Panadería'), ('5', 'Especias y Condimentos'), ('6', 'Productos Orgánicos'), ('7', 'Distribuidora de Bebidas'), ('8', 'Aves y Huevos'), ('9', 'Heladería'), ('10', 'Importadora de Productos Japoneses')], default=0, max_length=2)),
                ('promedio_calific', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
