# Generated by Django 4.2.7 on 2023-11-22 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedores', '0002_proveedor_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='categoria',
            field=models.CharField(choices=[('0', 'Sin categoría'), ('1', 'Proveedor de Frutas'), ('2', 'Carnicería'), ('3', 'Pescadería'), ('4', 'Panadería'), ('5', 'Especias y Condimentos'), ('6', 'Productos Orgánicos'), ('7', 'Distribuidora de Bebidas'), ('8', 'Aves y Huevos'), ('9', 'Heladería'), ('10', 'Importadora de Productos Japoneses')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
