# Generated by Django 4.2.7 on 2023-11-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_proveedor_categoria_alter_proveedor_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='promedio_calific',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
