# Generated by Django 4.2.7 on 2023-11-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_proveedor_promedio_calific'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='banner',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='icono',
            field=models.URLField(blank=True, null=True),
        ),
    ]
