# Generated by Django 4.2.7 on 2023-11-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_proveedor_banner_proveedor_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
