# Generated by Django 4.2.7 on 2023-11-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('1', 'Entregada'), ('2', 'Cancelada'), ('3', 'En camino'), ('4', 'Procesando'), ('5', 'Editando')], default=4, max_length=2),
        ),
        migrations.AlterField(
            model_name='orden',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
