# Generated by Django 4.2.7 on 2023-12-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenitem',
            name='estado',
            field=models.CharField(choices=[('0', 'Procesando'), ('1', 'Cancelado'), ('2', 'Aceptado')], default=0, max_length=2),
        ),
    ]
