# Generated by Django 4.2.7 on 2023-11-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_orden_estado_alter_orden_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenitem',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
