# Generated by Django 4.2.7 on 2023-11-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_ordenitem_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('0', 'Editando'), ('1', 'Pedido Realizado'), ('2', 'Enviado'), ('3', 'En Reparto'), ('4', 'Entregado')], default=0, max_length=2),
        ),
    ]
